//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThisCommVas
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkout
    {
        public int CheckoutId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> store_id { get; set; }
    
        public virtual products products { get; set; }
        public virtual stores stores { get; set; }
        public virtual users users { get; set; }
    }
}
