//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThisCommVas
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_image
    {
        public int id { get; set; }
        public byte[] image_path { get; set; }
        public int productID { get; set; }
    
        public virtual products products { get; set; }
    }
}
